---

- hosts: all
  become: true
  tasks:

  - name: copy files to apt distro machines
    tags: apt,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "Linux Mint" or ansible_distribution == "Ubuntu"

