---

- hosts: all
  become: true
  tasks:

  - name: update repository DEBIAN
    apt:
      update_cache: yes
    when: ansible_distribution == "Linux Mint" or ansible_distribution == "Ubuntu"

  - name: install apache2 package DEBIAN
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Linux Mint" or ansible_distribution == "Ubuntu"
        

  - name: add php support for apach DEBIAN
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Linux Mint" or ansible_distribution == "Ubuntu" 
    
  - name: update repository ROCKY
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache2 package ROCKY
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"


  - name: add php support for apache ROCKY
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Rocky"
